# Generated by Django 5.0.6 on 2024-06-16 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0004_alter_persona_edad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='donador',
        ),
    ]
