# Generated by Django 5.0.6 on 2024-06-16 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0005_remove_persona_donador'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='donador',
            field=models.BooleanField(default=None),
            preserve_default=False,
        ),
    ]
